### ISSUE TITLE
Installation fails in python 2, due to the setuptools

### ISSUE THREAD

**Issue by Costya-Y** [QualiSystems/cloudshell-shell-core#85]
Installation fails with a message:
      ************************************************************
      You are running Setuptools on Python 2, which is no longer
      supported and
      >>> SETUPTOOLS WILL STOP WORKING <<<
      in a subsequent release (no sooner than 2020-04-20).
      Please ensure you are installing
      Setuptools using pip 9.x or later or pin to `setuptools<45`
      in your environment.
      If you have done those things and are still encountering
      this message, please follow up at
      https://bit.ly/setuptools-py2-warning.
      ************************************************************
        sys.version_info < (3,) and warnings.warn(pre + "*" * 60 + msg + "*" * 60)
      warning: no files found matching '*.py' under directory 'tests'
      warning: no previously-included files found matching 'pyproject.toml'
      writing manifest file 'pip-egg-info\setuptools.egg-info\SOURCES.txt'
    Source in c:\windows\temp\pip-install-qtllru\setuptools has version 46.4.0, which satisfies requirement setuptools>=42 from http://localhost:8036/packages/setuptools-46.4.0.zip#md5=e2c6c3d64b38efe2e81bcd502cf54dcc
    Removed setuptools>=42 from http://localhost:8036/packages/setuptools-46.4.0.zip#md5=e2c6c3d64b38efe2e81bcd502cf54dcc from build tracker 'c:\\windows\\temp\\pip-req-tracker-qegr_5'
  Cleaning up...

I do not understand why pip is trying to download the incorrect version, but we need to fix it somehow

**Comment by Costya-Y** [comment]
The fix is in dev.

**Comment by alexquali** [comment]
Fixed in version 5.1.0
